### ISSUE TITLE
Types name are generated in a language other than English

### ISSUE THREAD

**Issue by skhrv** [cellular/oazapfts#262]
part of scheme:
```yaml
components:
  schemas:
    status:
      title: Детали заказа
      type: object
      properties:
        id:...

 ```

generated type:
```ts
export type ДеталиЗаказа = {
    id?: string;
};
```

Is it possible to make generate type name from title optional?
