### ISSUE TITLE
New Oazapfts version broke generated code: Need support for endpoint parameter of type Array

### ISSUE THREAD

**Issue by carleryd** [cellular/oazapfts#319]
First off, thanks a lot for building this library! It's helped us tremendously and I really appreciate your work.

I ran into an issue with existing Open API schema code when updating to latest 4.2 version.
My schema endpoint code looks like this

```
  /users/{userIds}:
    parameters:
      - name: userIds
        in: path
        explode: false
        required: true
        schema:
          type: array
          items:
            type: string
```

which when running `oazapfts` generates

```
export function getUsers(userIds: string[], opts?: Oazapfts.RequestOpts) {
...
    }>(`/users/${encodeURIComponent(userIds)}`, {
...
```

but `encodeURIComponent` does not accept array as argument. This broke after the introduction of https://github.com/cellular/oazapfts/pull/103. Before this change, the generated code looked the same except here were no `encodeURIComponent` applied to `orderIds`.

In the meantime I'm going back to an earlier version. Please let me know what you think, thanks!
